name: Kaboom
version: '${project.version}'
main: mrharpies.kaboom.Kaboom
api-version: 1.17
authors: [ MrHarpies ]
description: The Kaboom plugin is a fun way to troll other players. Use the comand kaboom for spawn a lighnig bolt and push the players in the air.
